### ISSUE TITLE
Can we turn off "plot_binning_results.py"?

### ISSUE THREAD

**Issue by Deanvik** [ursky/metaWRAP#510]
Hi!
I have metaWRAP binning and bin refinement working for several projects and very much appreciate it! The only issue I encounter is an error when trying to plot the bin refinement results. This is no problem really as we still get the bins and stats etc... however I have this included in a Snakemake pipeline and the missing files makes snakemake freakout and try to delete everything (it doesn't - cant delete populated directories - but does throw annoying errors and cost time). Can we just not plot the figures somehow?

error message below:

------------------------------------------------------------------------------------------------------------------------
-----                      making completion and contamination ranking plots of final outputs                      -----
------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/metaWRAP/bin//metawrap-scripts/plot_binning_results.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 62, in pylab_setup
    [backend_name], 0)
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import (
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 19, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 54, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/opt/conda/lib/python2.7/site-packages/matplotlib/backends/qt_compat.py", line 140, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
mv: cannot stat 'binning_results.eps': No such file or directory
mv: cannot stat 'binning_results.png': No such file or directory

**Comment by ursky** [comment]
Just find the bash script that calls on `plot_binning_results.py` and delete that line (should be in your `metawrap-modules/binning.sh`).
