### ISSUE TITLE
Something went wrong with estimating fragment abundance

### ISSUE THREAD

**Issue by JipengLuo** [ursky/metaWRAP#536]
When i use metaWRAP v=1.3.2 to run binning module in Miniconda3. The maxbin2 and metabat2 ran well, but something wrong with the CONCOCT, it showed that Something went wrong with estimating fragment abundance. Exiting... 
Below is the specific errors:
Traceback (most recent call last):
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/bin/concoct_coverage_table.py", line 18, in <module>
    import pandas as pd
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/pandas/compat/__init__.py", line 439, in <module>
    from dateutil import parser as _date_parser
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo, ParserError
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/dateutil/parser/_parser.py", line 50, in <module>
    from .. import tz
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/dateutil/tz/__init__.py", line 2, in <module>
    from .tz import *
  File "/N/u/luojip/Quartz/miniconda3/envs/metawrap-env/lib/python2.7/site-packages/dateutil/tz/tz.py", line 21, in <module>
    from six.moves import _thread
  File "/N/soft/rhel8/xalt/2.10.34/site_packages/sitecustomize.py", line 70, in find_module
    path = result.origin
AttributeError: '_SixMetaPathImporter' object has no attribute 'origin'.

It seems something wrong with 'SixMetaPathImporter', when i updated the six package, the same error showed again.
Did anybody meet with such problems? Need help.

Jipeng

**Comment by quliping** [comment]
I also had some problems for running CONCOCT, and I just use the other binninig tool (vamb) rather than CONCOCT... I run maxbin2 and metabat2 using metawrap, and vamb by myself, then I get the final be set using the bin_refinement module of metawrap.
